In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

C:\Users\User\AppData\Local\Temp\ipykernel_3032\3477112522.py:1: DtypeWarning: Columns (6,16,23,48,49,50,51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data.csv")

In [17]:
columns = df.columns
columns
selected_columns_df = df[["OrderId","OrderCode","OrderDate","CustomerID","TotalPrice","AfterPromoPrice","PromoPrice","GrandTotalPrice"]]
selected_columns_df

,OrderId,OrderCode,OrderDate,CustomerID,TotalPrice,AfterPromoPrice,PromoPrice,GrandTotalPrice
0,79,3f1ca311-28dd-42ae-be4f-b01173119087,2022-09-15 04:39:23.800880,6e4fb72e-2cdc-47ad-a4db-0b04e0f83d59,3090.0,0.0,0.0,3090.0
1,80,8c9fb2f1-7339-4ca1-89f8-767b989d7c55,2022-09-15 08:07:53.338027,91a9b569-2342-45dc-8c52-2d2a41176552,3398.0,0.0,0.0,3398.0
2,81,d8591ac9-be1d-4200-bfee-71cd1a4451a2,2022-09-15 10:48:29.721237,6e21e444-d5bf-4b3a-ac5b-4599bc2f9b9c,649.0,0.0,0.0,649.0
3,82,1ce4c26a-e72e-46c1-b362-0977a0b69996,2022-09-15 11:13:53.887009,8ad5f47e-191f-43ac-81e1-75895bba4f7d,939.0,0.0,0.0,939.0
4,83,05bca283-83fd-4921-923a-69541b9e62ad,2022-09-15 11:39:46.833212,b9fe25b5-e4c6-4535-b4a8-17208802e342,330.0,0.0,0.0,390.0
...,...,...,...,...,...,...,...,...
16385,16523,8577f9e1-2c54-40ae-ab46-d566c8887c55,2023-08-21 22:53:32.868948,15d50fe0-5e30-4d28-9984-242cdcccfcd4,1450.0,1450.0,0.0,1570.0
16386,16524,1cf36c20-5cdc-466a-9ec7-561986e063bd,2023-08-22 19:06:48.672781,d0539f2d-68d5-47fc-aee6-4c7ff3f6d96b,1350.0,1350.0,0.0,1410.0
16387,16525,fa1b75a3-6623-4e38-9ee8-42eb8072ae20,2023-08-23 02:39:08.245645,53d500ce-bb3f-4076-b472-a3290bfff7c9,149.4,149.0,0.0,269.4
16388,16526,a21fa0d8-eba3-4d7c-85f2-f95c287d63cf,2023-08-25 02:12:08.303716,a4eb8bcd-f786-4473-a381-a93e01bfe24b,700.0,700.0,0.0,760.0
16389,16527,73d06d5f-9efd-4e49-aa06-f0b5120c85a8,2023-08-26 13:58:43.161232,d28a6512-9b7d-4639-a8af-d68014c46691,550.0,550.0,0.0,610.0

In [22]:
duplicate_df = selected_columns_df.duplicated(keep=False)
print(duplicate_df)

0        False
1        False
2        False
3        False
4        False
         ...
16385    False
16386    False
16387    False
16388    False
16389    False
Length: 16390, dtype: bool